### ISSUE TITLE
area_covered

### ISSUE THREAD

**Issue by OIQuinn** [lshtm-gis/WHO_PHSM_Cleaning#92]
area_covered equalling other countries. 
For example, in the Iraq file, Kuwait and Bahrain appear as area_covered. This should national and in the target.

example id: `ACAPS_160049`

**Comment by hamishgibbs** [comment]
I am seeing this issue in the input ACAPS data. 

Another example is ACAPS `prop_id` == `118395` where `country_territory_area` == "With Iran" which is a country and definitely not an administrative region of Iraq. 

I think that this miscoding is best addressed by volunteers because of the possible variation in administrative areas. I don't think I can really address the issue automatically at the moment.

**Comment by hamishgibbs** [comment]
What are your thoughts?

**Comment by hamishgibbs** [comment]
As this is an issue with ACAPS data as it is delivered I will close it here for now.
